repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks: # general hooks
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      #      - id: debug-statements # Can't use because of the way the debugger is imported (only when DEBUG = True)
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: \.ts$
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff
        args: [
          '--fix',
          '--target-version', 'py311',
          '--select', 'E,F,UP,W',
          '--ignore', 'E501',
        ]
      - id: ruff-format
        args: [ '--target-version', 'py311' ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      # Critical mandatory checks from QGIS plugin repository that prevent publishing a new version of the plugin
      # Keep in sync with critical ones in https://github.com/qgis/QGIS-Plugins-Website/blob/master/qgis-app/plugins/management/commands/data/bandit_rules.json
      - id: bandit
        args: [ "-t", "B102,B103,B105,B106,B107,B201,B202,B301,B302,B304,B305,B306,B307,B312,B321,B323,B401,B402,B412,B413,B501,B502,B503,B505,B506,B507,B601,B602,B604,B605,B609,B610,B611,B612,B613,B701", "-x", "SEILAPLAN/tests/" ]
