# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swissgeodatadownloader_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SwissGeodataDownloaderDockWidgetBase(object):
    def setupUi(self, SwissGeodataDownloaderDockWidgetBase):
        SwissGeodataDownloaderDockWidgetBase.setObjectName("SwissGeodataDownloaderDockWidgetBase")
        SwissGeodataDownloaderDockWidgetBase.resize(467, 864)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.guiGroupSearch = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guiGroupSearch.setFont(font)
        self.guiGroupSearch.setObjectName("guiGroupSearch")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.guiGroupSearch)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.guiSearchField = QtWidgets.QLineEdit(self.guiGroupSearch)
        self.guiSearchField.setObjectName("guiSearchField")
        self.verticalLayout_3.addWidget(self.guiSearchField)
        self.guiDatasetList = QtWidgets.QListWidget(self.guiGroupSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guiDatasetList.sizePolicy().hasHeightForWidth())
        self.guiDatasetList.setSizePolicy(sizePolicy)
        self.guiDatasetList.setMaximumSize(QtCore.QSize(16777215, 1600))
        self.guiDatasetList.setAlternatingRowColors(False)
        self.guiDatasetList.setObjectName("guiDatasetList")
        self.verticalLayout_3.addWidget(self.guiDatasetList)
        self.verticalLayout.addWidget(self.guiGroupSearch)
        self.guiGroupOptions = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.guiGroupOptions.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.guiGroupOptions.setFont(font)
        self.guiGroupOptions.setFlat(False)
        self.guiGroupOptions.setCheckable(False)
        self.guiGroupOptions.setObjectName("guiGroupOptions")
        self.formLayout = QtWidgets.QFormLayout(self.guiGroupOptions)
        self.formLayout.setObjectName("formLayout")
        self.guiFormatL = QtWidgets.QLabel(self.guiGroupOptions)
        self.guiFormatL.setObjectName("guiFormatL")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.guiFormatL)
        self.guiFormat = QtWidgets.QComboBox(self.guiGroupOptions)
        self.guiFormat.setObjectName("guiFormat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.guiFormat)
        self.guiResolutionL = QtWidgets.QLabel(self.guiGroupOptions)
        self.guiResolutionL.setObjectName("guiResolutionL")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.guiResolutionL)
        self.guiResolution = QtWidgets.QComboBox(self.guiGroupOptions)
        self.guiResolution.setObjectName("guiResolution")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.guiResolution)
        self.guiCoordsysL = QtWidgets.QLabel(self.guiGroupOptions)
        self.guiCoordsysL.setObjectName("guiCoordsysL")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.guiCoordsysL)
        self.guiCoordsys = QtWidgets.QComboBox(self.guiGroupOptions)
        self.guiCoordsys.setObjectName("guiCoordsys")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.guiCoordsys)
        self.guiTimestampL = QtWidgets.QLabel(self.guiGroupOptions)
        self.guiTimestampL.setObjectName("guiTimestampL")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.guiTimestampL)
        self.guiTimestamp = QtWidgets.QComboBox(self.guiGroupOptions)
        self.guiTimestamp.setObjectName("guiTimestamp")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.guiTimestamp)
        self.verticalLayout.addWidget(self.guiGroupOptions)
        self.guiGroupExtent = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.guiGroupExtent.setObjectName("guiGroupExtent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.guiGroupExtent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.guiExtentWidget = gui.QgsExtentGroupBox(self.guiGroupExtent)
        self.guiExtentWidget.setTitleBase("")
        self.guiExtentWidget.setObjectName("guiExtentWidget")
        self.verticalLayout_2.addWidget(self.guiExtentWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.guiFullExtentChbox = QtWidgets.QCheckBox(self.guiGroupExtent)
        self.guiFullExtentChbox.setObjectName("guiFullExtentChbox")
        self.horizontalLayout_2.addWidget(self.guiFullExtentChbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.guiGroupExtent)
        self.guiGroupFiles = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.guiGroupFiles.setObjectName("guiGroupFiles")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.guiGroupFiles)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.guiRequestListBtn = QtWidgets.QPushButton(self.guiGroupFiles)
        self.guiRequestListBtn.setObjectName("guiRequestListBtn")
        self.horizontalLayout_3.addWidget(self.guiRequestListBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.guiLabel23 = QtWidgets.QLabel(self.guiGroupFiles)
        self.guiLabel23.setObjectName("guiLabel23")
        self.horizontalLayout_3.addWidget(self.guiLabel23)
        self.guiFileType = QtWidgets.QComboBox(self.guiGroupFiles)
        self.guiFileType.setObjectName("guiFileType")
        self.horizontalLayout_3.addWidget(self.guiFileType)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.guiFileList = QtWidgets.QListWidget(self.guiGroupFiles)
        self.guiFileList.setObjectName("guiFileList")
        self.verticalLayout_4.addWidget(self.guiFileList)
        self.guiFileListStatus = QtWidgets.QLabel(self.guiGroupFiles)
        self.guiFileListStatus.setText("")
        self.guiFileListStatus.setObjectName("guiFileListStatus")
        self.verticalLayout_4.addWidget(self.guiFileListStatus)
        self.verticalLayout.addWidget(self.guiGroupFiles)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.guiDownloadBtn = QtWidgets.QPushButton(self.dockWidgetContents)
        self.guiDownloadBtn.setObjectName("guiDownloadBtn")
        self.horizontalLayout.addWidget(self.guiDownloadBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        SwissGeodataDownloaderDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(SwissGeodataDownloaderDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(SwissGeodataDownloaderDockWidgetBase)

    def retranslateUi(self, SwissGeodataDownloaderDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        SwissGeodataDownloaderDockWidgetBase.setWindowTitle(_translate("SwissGeodataDownloaderDockWidgetBase", "swiss geodata downloader"))
        self.guiGroupSearch.setTitle(_translate("SwissGeodataDownloaderDockWidgetBase", "1. Dataset"))
        self.guiSearchField.setPlaceholderText(_translate("SwissGeodataDownloaderDockWidgetBase", "Search for dataset..."))
        self.guiGroupOptions.setTitle(_translate("SwissGeodataDownloaderDockWidgetBase", "2. Options"))
        self.guiFormatL.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Format"))
        self.guiResolutionL.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Resolution [m]"))
        self.guiCoordsysL.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Coord.sys"))
        self.guiTimestampL.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Timestamp"))
        self.guiGroupExtent.setTitle(_translate("SwissGeodataDownloaderDockWidgetBase", "3. Extent"))
        self.guiFullExtentChbox.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Full datset extent"))
        self.guiGroupFiles.setTitle(_translate("SwissGeodataDownloaderDockWidgetBase", "4. Files"))
        self.guiRequestListBtn.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Request file list"))
        self.guiLabel23.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Filter by type"))
        self.guiDownloadBtn.setText(_translate("SwissGeodataDownloaderDockWidgetBase", "Download"))
from qgis import gui
